LibStub("LibCraftCategories-1.0").ruRU = {
  [25]={["Name_lang"]="Готовим с чувством",["HordeName_lang"]="",["ID"]=71,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=6,["Flags"]=0},
  [128]={["Name_lang"]="Руны",["HordeName_lang"]="",["ID"]=210,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=960,["OrderIndex"]=0,["Flags"]=0},
  [186]={["Name_lang"]="Древние алхимические рецепты",["HordeName_lang"]="",["ID"]=337,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=100,["Flags"]=0},
  [198]={["Name_lang"]="Старинные чары",["HordeName_lang"]="",["ID"]=353,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=1000,["Flags"]=0},
  [231]={["Name_lang"]="Старинные чертежи",["HordeName_lang"]="",["ID"]=395,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=100,["Flags"]=0},
  [232]={["Name_lang"]="Дренорские лекарства",["HordeName_lang"]="",["ID"]=396,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=10,["Flags"]=0},
  [233]={["Name_lang"]="Старинные снадобья",["HordeName_lang"]="",["ID"]=397,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=100,["Flags"]=0},
  [234]={["Name_lang"]="Иллюзии",["HordeName_lang"]="",["ID"]=399,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [238]={["Name_lang"]="Торговые векселя",["HordeName_lang"]="",["ID"]=403,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=20,["Flags"]=0},
  [239]={["Name_lang"]="Удаление",["HordeName_lang"]="",["ID"]=404,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [255]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=424,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=0,["Flags"]=0},
  [263]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=432,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=0,["Flags"]=0},
  [294]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=468,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=0,["Flags"]=0},
  [307]={["Name_lang"]="Лекарства Расколотых островов",["HordeName_lang"]="",["ID"]=481,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=5,["Flags"]=0},
  [327]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=536,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=0,["Flags"]=0},
  [328]={["Name_lang"]="Кул-тирасское кузнечное дело - заголовок",["HordeName_lang"]="Зандаларское кузнечное дело - заголовок",["ID"]=541,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=930,["Flags"]=0},
  [330]={["Name_lang"]="Чертежи Legion - заголовок",["HordeName_lang"]="",["ID"]=545,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=940,["Flags"]=0},
  [335]={["Name_lang"]="Дренорские чертежи - заголовок",["HordeName_lang"]="",["ID"]=551,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=950,["Flags"]=0},
  [336]={["Name_lang"]="Чертежи пандаренов - заголовок",["HordeName_lang"]="",["ID"]=552,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=960,["Flags"]=0},
  [351]={["Name_lang"]="Чертежи времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=568,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=970,["Flags"]=0},
  [359]={["Name_lang"]="Чертежи Нордскола - заголовок",["HordeName_lang"]="",["ID"]=576,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=980,["Flags"]=0},
  [366]={["Name_lang"]="Чертежи Запределья - заголовок",["HordeName_lang"]="",["ID"]=583,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=990,["Flags"]=0},
  [371]={["Name_lang"]="Классические чертежи - заголовок",["HordeName_lang"]="",["ID"]=589,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=999,["Flags"]=0},
  [373]={["Name_lang"]="Кул-тирасская алхимия - заголовок",["HordeName_lang"]="Зандаларская алхимия - заголовок",["ID"]=591,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=930,["Flags"]=0},
  [375]={["Name_lang"]="Алхимия Расколотых островов - заголовок",["HordeName_lang"]="",["ID"]=593,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=940,["Flags"]=0},
  [376]={["Name_lang"]="Дренорская алхимия - заголовок",["HordeName_lang"]="",["ID"]=594,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=950,["Flags"]=0},
  [377]={["Name_lang"]="Пандарийская алхимия - заголовок",["HordeName_lang"]="",["ID"]=595,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=960,["Flags"]=0},
  [379]={["Name_lang"]="Алхимия времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=597,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=970,["Flags"]=0},
  [381]={["Name_lang"]="Алхимия Нордскола - заголовок",["HordeName_lang"]="",["ID"]=599,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=980,["Flags"]=0},
  [383]={["Name_lang"]="Алхимия Запределья - заголовок",["HordeName_lang"]="",["ID"]=601,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=990,["Flags"]=0},
  [385]={["Name_lang"]="Классическая алхимия - заголовок",["HordeName_lang"]="",["ID"]=603,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=999,["Flags"]=0},
  [428]={["Name_lang"]="Кул-тирасское наложение чар - заголовок",["HordeName_lang"]="Зандаларское наложение чар - заголовок",["ID"]=646,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=930,["Flags"]=0},
  [430]={["Name_lang"]="Дренорское наложение чар - заголовок",["HordeName_lang"]="",["ID"]=648,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=950,["Flags"]=0},
  [431]={["Name_lang"]="Наложение чар Legion - заголовок",["HordeName_lang"]="",["ID"]=649,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=940,["Flags"]=0},
  [437]={["Name_lang"]="Наложение чар Пандарии - заголовок",["HordeName_lang"]="",["ID"]=655,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=960,["Flags"]=0},
  [442]={["Name_lang"]="Наложение чар времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=660,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=970,["Flags"]=0},
  [444]={["Name_lang"]="Наложение чар Нордскола - заголовок",["HordeName_lang"]="",["ID"]=662,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=980,["Flags"]=0},
  [446]={["Name_lang"]="Наложение чар Запределья - заголовок",["HordeName_lang"]="",["ID"]=664,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=990,["Flags"]=0},
  [448]={["Name_lang"]="Классическое наложение чар - заголовок",["HordeName_lang"]="",["ID"]=666,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=999,["Flags"]=0},
  [490]={["Name_lang"]="Кул-тирасское инженерное дело - заголовок",["HordeName_lang"]="Зандаларское инженерное дело - заголовок",["ID"]=708,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=930,["Flags"]=0},
  [492]={["Name_lang"]="Инженерное дело Legion - заголовок",["HordeName_lang"]="",["ID"]=710,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=940,["Flags"]=0},
  [493]={["Name_lang"]="Дренорское инженерное дело - заголовок",["HordeName_lang"]="",["ID"]=711,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=950,["Flags"]=0},
  [494]={["Name_lang"]="Инженерное дело Пандарии - заголовок",["HordeName_lang"]="",["ID"]=712,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=960,["Flags"]=0},
  [496]={["Name_lang"]="Инженерное дело времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=714,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=970,["Flags"]=0},
  [498]={["Name_lang"]="Инженерное дело Нордскола - заголовок",["HordeName_lang"]="",["ID"]=716,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=980,["Flags"]=0},
  [500]={["Name_lang"]="Инженерное дело Запределья - заголовок",["HordeName_lang"]="",["ID"]=718,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=990,["Flags"]=0},
  [502]={["Name_lang"]="Классическое инженерное дело - заголовок",["HordeName_lang"]="",["ID"]=720,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=999,["Flags"]=0},
  [540]={["Name_lang"]="Кул-тирасское начертание - заголовок",["HordeName_lang"]="Зандаларское начертание - заголовок",["ID"]=758,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=930,["Flags"]=0},
  [542]={["Name_lang"]="Начертание Legion - заголовок",["HordeName_lang"]="",["ID"]=760,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=940,["Flags"]=0},
  [543]={["Name_lang"]="Дренорское начертание - заголовок",["HordeName_lang"]="",["ID"]=761,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=950,["Flags"]=0},
  [544]={["Name_lang"]="Начертание Пандарии - заголовок",["HordeName_lang"]="",["ID"]=762,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=960,["Flags"]=0},
  [546]={["Name_lang"]="Начертание времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=764,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=970,["Flags"]=0},
  [548]={["Name_lang"]="Начертание Нордскола - заголовок",["HordeName_lang"]="",["ID"]=766,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=980,["Flags"]=0},
  [550]={["Name_lang"]="Начертание Запределья - заголовок",["HordeName_lang"]="",["ID"]=768,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=990,["Flags"]=0},
  [552]={["Name_lang"]="Классическое начертание - заголовок",["HordeName_lang"]="",["ID"]=770,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=999,["Flags"]=0},
  [586]={["Name_lang"]="Кул-тирасские эскизы - заголовок",["HordeName_lang"]="Зандаларские эскизы - заголовок",["ID"]=804,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=930,["Flags"]=0},
  [588]={["Name_lang"]="Эскизы Legion - заголовок",["HordeName_lang"]="",["ID"]=806,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=940,["Flags"]=0},
  [589]={["Name_lang"]="Дренорские эскизы - заголовок",["HordeName_lang"]="",["ID"]=807,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=950,["Flags"]=0},
  [590]={["Name_lang"]="Пандарийские эскизы - заголовок",["HordeName_lang"]="",["ID"]=808,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=960,["Flags"]=0},
  [592]={["Name_lang"]="Эскизы времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=810,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=970,["Flags"]=0},
  [594]={["Name_lang"]="Эскизы Нордскола - заголовок",["HordeName_lang"]="",["ID"]=812,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=980,["Flags"]=0},
  [596]={["Name_lang"]="Эскизы Запределья - заголовок",["HordeName_lang"]="",["ID"]=814,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=990,["Flags"]=0},
  [598]={["Name_lang"]="Классические эскизы - заголовок",["HordeName_lang"]="",["ID"]=816,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=999,["Flags"]=0},
  [652]={["Name_lang"]="Кул-тирасские выкройки - заголовок",["HordeName_lang"]="Зандаларские выкройки - заголовок",["ID"]=870,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=930,["Flags"]=0},
  [654]={["Name_lang"]="Выкройки Legion - заголовок",["HordeName_lang"]="",["ID"]=872,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=940,["Flags"]=0},
  [655]={["Name_lang"]="Дренорские выкройки - заголовок",["HordeName_lang"]="",["ID"]=873,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=950,["Flags"]=0},
  [656]={["Name_lang"]="Классические выкройки - заголовок",["HordeName_lang"]="",["ID"]=874,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=999,["Flags"]=0},
  [657]={["Name_lang"]="Пандарийские выкройки - заголовок",["HordeName_lang"]="",["ID"]=875,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=960,["Flags"]=0},
  [659]={["Name_lang"]="Выкройки времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=877,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=970,["Flags"]=0},
  [661]={["Name_lang"]="Выкройки Нордскола - заголовок",["HordeName_lang"]="",["ID"]=879,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=980,["Flags"]=0},
  [663]={["Name_lang"]="Выкройки Запределья - заголовок",["HordeName_lang"]="",["ID"]=881,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=990,["Flags"]=0},
  [723]={["Name_lang"]="Кул-тирасские выкройки - заголовок",["HordeName_lang"]="Зандаларские выкройки - заголовок",["ID"]=941,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=930,["Flags"]=0},
  [729]={["Name_lang"]="Выкройки Legion - заголовок",["HordeName_lang"]="",["ID"]=947,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=940,["Flags"]=0},
  [730]={["Name_lang"]="Дренорские выкройки - заголовок",["HordeName_lang"]="",["ID"]=948,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=950,["Flags"]=0},
  [731]={["Name_lang"]="Пандарийские выкройки - заголовок",["HordeName_lang"]="",["ID"]=949,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=960,["Flags"]=0},
  [733]={["Name_lang"]="Выкройки времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=951,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=970,["Flags"]=0},
  [735]={["Name_lang"]="Выкройки Нордскола - заголовок",["HordeName_lang"]="",["ID"]=953,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=980,["Flags"]=0},
  [737]={["Name_lang"]="Выкройки Запределья - заголовок",["HordeName_lang"]="",["ID"]=955,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=990,["Flags"]=0},
  [739]={["Name_lang"]="Классические выкройки - заголовок",["HordeName_lang"]="",["ID"]=957,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=999,["Flags"]=0},
  [795]={["Name_lang"]="Дренорская кухня - заголовок",["HordeName_lang"]="",["ID"]=1013,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=950,["Flags"]=0},
  [796]={["Name_lang"]="Блюда Расколотых островов - заголовок",["HordeName_lang"]="",["ID"]=1014,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=940,["Flags"]=0},
  [797]={["Name_lang"]="Пандаренские деликатесы - заголовок",["HordeName_lang"]="",["ID"]=1015,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=960,["Flags"]=0},
  [798]={["Name_lang"]="Рецепты старого мира - заголовок",["HordeName_lang"]="",["ID"]=1016,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=999,["Flags"]=0},
  [799]={["Name_lang"]="Блюда Запределья - заголовок",["HordeName_lang"]="",["ID"]=1017,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=990,["Flags"]=0},
  [800]={["Name_lang"]="Рецепты далекого Севера - заголовок",["HordeName_lang"]="",["ID"]=1018,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=980,["Flags"]=0},
  [801]={["Name_lang"]="Рецепты времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=1019,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=970,["Flags"]=0},
  [810]={["Name_lang"]="Кул-тирасское травничество - заголовок",["HordeName_lang"]="Зандаларское травничество - заголовок",["ID"]=1028,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=930,["Flags"]=0},
  [813]={["Name_lang"]="Травничество Legion - заголовок",["HordeName_lang"]="",["ID"]=1031,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=940,["Flags"]=0},
  [815]={["Name_lang"]="Травничество Дренора - заголовок",["HordeName_lang"]="",["ID"]=1033,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=950,["Flags"]=0},
  [817]={["Name_lang"]="Травничество Пандарии - заголовок",["HordeName_lang"]="",["ID"]=1035,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=960,["Flags"]=0},
  [819]={["Name_lang"]="Травничество времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=1037,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=970,["Flags"]=0},
  [821]={["Name_lang"]="Травничество Нордскола - заголовок",["HordeName_lang"]="",["ID"]=1039,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=980,["Flags"]=0},
  [823]={["Name_lang"]="Травничество Запределья - заголовок",["HordeName_lang"]="",["ID"]=1041,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=990,["Flags"]=0},
  [825]={["Name_lang"]="Классическое травничество - заголовок",["HordeName_lang"]="",["ID"]=1043,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=999,["Flags"]=0},
  [827]={["Name_lang"]="Кул-тирасское снятие шкур - заголовок",["HordeName_lang"]="Зандаларское снятие шкур - заголовок",["ID"]=1045,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=930,["Flags"]=0},
  [829]={["Name_lang"]="Снятие шкур Legion - заголовок",["HordeName_lang"]="",["ID"]=1047,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=940,["Flags"]=0},
  [830]={["Name_lang"]="Снятие шкур на Дреноре - заголовок",["HordeName_lang"]="",["ID"]=1049,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=950,["Flags"]=0},
  [832]={["Name_lang"]="Снятие шкур в Пандарии - заголовок",["HordeName_lang"]="",["ID"]=1051,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=960,["Flags"]=0},
  [834]={["Name_lang"]="Снятие шкур времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=1053,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=970,["Flags"]=0},
  [836]={["Name_lang"]="Снятие шкур в Нордсколе - заголовок",["HordeName_lang"]="",["ID"]=1055,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=980,["Flags"]=0},
  [838]={["Name_lang"]="Снятие шкур в Запределье - заголовок",["HordeName_lang"]="",["ID"]=1057,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=990,["Flags"]=0},
  [840]={["Name_lang"]="Классическое снятие шкур - заголовок",["HordeName_lang"]="",["ID"]=1059,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=999,["Flags"]=0},
  [844]={["Name_lang"]="Кул-тирасское горное дело - заголовок",["HordeName_lang"]="Зандаларское горное дело - заголовок",["ID"]=1064,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=930,["Flags"]=0},
  [846]={["Name_lang"]="Горное дело Legion - заголовок",["HordeName_lang"]="",["ID"]=1066,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=940,["Flags"]=0},
  [847]={["Name_lang"]="Горное дело Дренора - заголовок",["HordeName_lang"]="",["ID"]=1067,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=950,["Flags"]=0},
  [849]={["Name_lang"]="Горное дело Пандарии - заголовок",["HordeName_lang"]="",["ID"]=1069,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=960,["Flags"]=0},
  [851]={["Name_lang"]="Горное дело времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=1071,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=970,["Flags"]=0},
  [853]={["Name_lang"]="Горное дело Нордскола - заголовок",["HordeName_lang"]="",["ID"]=1073,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=980,["Flags"]=0},
  [855]={["Name_lang"]="Горное дело Запределья - заголовок",["HordeName_lang"]="",["ID"]=1075,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=990,["Flags"]=0},
  [857]={["Name_lang"]="Классическое горное дело - заголовок",["HordeName_lang"]="",["ID"]=1077,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=999,["Flags"]=0},
  [877]={["Name_lang"]="Классическая рыбная ловля - заголовок",["HordeName_lang"]="",["ID"]=1099,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=1000,["Flags"]=0},
  [879]={["Name_lang"]="Рыбная ловля в Запределье - заголовок",["HordeName_lang"]="",["ID"]=1101,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=990,["Flags"]=0},
  [881]={["Name_lang"]="Рыбная ловля Нордскола - заголовок",["HordeName_lang"]="",["ID"]=1103,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=980,["Flags"]=0},
  [883]={["Name_lang"]="Рыбная ловля времен Катаклизма - заголовок",["HordeName_lang"]="",["ID"]=1105,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=970,["Flags"]=0},
  [885]={["Name_lang"]="Пандарийская рыбная ловля - заголовок",["HordeName_lang"]="",["ID"]=1107,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=960,["Flags"]=0},
  [887]={["Name_lang"]="Дренорская рыбная ловля - заголовок",["HordeName_lang"]="",["ID"]=1109,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=950,["Flags"]=0},
  [889]={["Name_lang"]="Рыбная ловля Legion - заголовок",["HordeName_lang"]="",["ID"]=1111,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=940,["Flags"]=0},
  [891]={["Name_lang"]="Кул-тирасская рыбная ловля - заголовок",["HordeName_lang"]="Зандаларская рыбная ловля - заголовок",["ID"]=1113,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=930,["Flags"]=0},
  [895]={["Name_lang"]="Кул-тирасская кухня - заголовок",["HordeName_lang"]="Зандаларская кухня - заголовок",["ID"]=1117,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=930,["Flags"]=0},
  [929]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=1250,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=0,["Flags"]=0},
  [932]={["Name_lang"]="Тренировка",["HordeName_lang"]="",["ID"]=1255,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [934]={["Name_lang"]="Кустарная механика",["HordeName_lang"]="",["ID"]=1257,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2720,["OrderIndex"]=0,["Flags"]=0},
  [954]={["Name_lang"]="Shadowlands Alchemy - Header",["HordeName_lang"]="",["ID"]=1293,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=940,["Flags"]=0},
  [971]={["Name_lang"]="Shadowlands Blacksmithing - Header",["HordeName_lang"]="",["ID"]=1310,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=920,["Flags"]=0},
  [980]={["Name_lang"]="Shadowlands Mining - Header",["HordeName_lang"]="",["ID"]=1319,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=920,["Flags"]=0},
  [983]={["Name_lang"]="Shadowlands Cuisine - Header",["HordeName_lang"]="",["ID"]=1322,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=920,["Flags"]=0},
  [989]={["Name_lang"]="Shadowlands Skinning - Header",["HordeName_lang"]="",["ID"]=1330,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=920,["Flags"]=0},
  [992]={["Name_lang"]="Shadowlands Leatherworking - Header",["HordeName_lang"]="",["ID"]=1333,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=920,["Flags"]=0},
  [1007]={["Name_lang"]="Shadowlands Enchanting - Header",["HordeName_lang"]="",["ID"]=1363,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=920,["Flags"]=0},
  [1020]={["Name_lang"]="Shadowlands Engineering - Header",["HordeName_lang"]="",["ID"]=1380,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=920,["Flags"]=0},
  [1030]={["Name_lang"]="Shadowlands Fishing - Header",["HordeName_lang"]="",["ID"]=1390,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=920,["Flags"]=0},
  [1034]={["Name_lang"]="Shadowlands Tailoring - Header",["HordeName_lang"]="",["ID"]=1394,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=0,["Flags"]=0},
  [1044]={["Name_lang"]="Shadowlands Inscription - Header",["HordeName_lang"]="",["ID"]=1405,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=920,["Flags"]=0},
  [1055]={["Name_lang"]="Shadowlands Designs - Header",["HordeName_lang"]="",["ID"]=1417,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=920,["Flags"]=0},
  [1065]={["Name_lang"]="Shadowlands Herbalism - Header",["HordeName_lang"]="",["ID"]=1442,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=920,["Flags"]=0},
  [1067]={["Name_lang"]="Тайнопись душ",["HordeName_lang"]="",["ID"]=1444,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2777,["OrderIndex"]=0,["Flags"]=0},
  [1080]={["Name_lang"]="Сшивание поганищ",["HordeName_lang"]="",["ID"]=1478,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2787,["OrderIndex"]=0,["Flags"]=0},
  [1085]={["Name_lang"]="Путь перерождения",["HordeName_lang"]="",["ID"]=1485,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2791,["OrderIndex"]=0,["Flags"]=0},
}