LibStub("LibCraftCategories-1.0").zhTW = {
  [25]={["Name_lang"]="憑感覺做菜",["HordeName_lang"]="",["ID"]=71,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=6,["Flags"]=0},
  [128]={["Name_lang"]="符文",["HordeName_lang"]="",["ID"]=210,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=960,["OrderIndex"]=0,["Flags"]=0},
  [186]={["Name_lang"]="古老的鍊金術配方",["HordeName_lang"]="",["ID"]=337,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=100,["Flags"]=0},
  [198]={["Name_lang"]="古老的附魔",["HordeName_lang"]="",["ID"]=353,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=1000,["Flags"]=0},
  [231]={["Name_lang"]="古老的設計圖",["HordeName_lang"]="",["ID"]=395,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=100,["Flags"]=0},
  [232]={["Name_lang"]="德拉諾的藥品",["HordeName_lang"]="",["ID"]=396,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=10,["Flags"]=0},
  [233]={["Name_lang"]="舊的藥方",["HordeName_lang"]="",["ID"]=397,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=100,["Flags"]=0},
  [234]={["Name_lang"]="幻象",["HordeName_lang"]="",["ID"]=399,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [238]={["Name_lang"]="貿易訂單",["HordeName_lang"]="",["ID"]=403,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=20,["Flags"]=0},
  [239]={["Name_lang"]="移除",["HordeName_lang"]="",["ID"]=404,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [255]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=424,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=0,["Flags"]=0},
  [263]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=432,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=0,["Flags"]=0},
  [294]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=468,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=0,["Flags"]=0},
  [307]={["Name_lang"]="破碎群島的藥品",["HordeName_lang"]="",["ID"]=481,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=129,["OrderIndex"]=5,["Flags"]=0},
  [327]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=536,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=0,["Flags"]=0},
  [328]={["Name_lang"]="庫爾提拉斯鍛造 - 標題",["HordeName_lang"]="贊達拉鍛造 - 標題",["ID"]=541,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=930,["Flags"]=0},
  [330]={["Name_lang"]="軍團設計圖 - 標題",["HordeName_lang"]="",["ID"]=545,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=940,["Flags"]=0},
  [335]={["Name_lang"]="德拉諾設計圖 - 標題",["HordeName_lang"]="",["ID"]=551,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=950,["Flags"]=0},
  [336]={["Name_lang"]="熊貓人設計圖 - 標題",["HordeName_lang"]="",["ID"]=552,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=960,["Flags"]=0},
  [351]={["Name_lang"]="大災變設計圖 - 標題",["HordeName_lang"]="",["ID"]=568,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=970,["Flags"]=0},
  [359]={["Name_lang"]="北裂境設計圖 - 標題",["HordeName_lang"]="",["ID"]=576,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=980,["Flags"]=0},
  [366]={["Name_lang"]="外域設計圖 - 標題",["HordeName_lang"]="",["ID"]=583,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=990,["Flags"]=0},
  [371]={["Name_lang"]="艾澤拉斯設計圖 - 標題",["HordeName_lang"]="",["ID"]=589,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=999,["Flags"]=0},
  [373]={["Name_lang"]="庫爾提拉斯鍊金術 - 標題",["HordeName_lang"]="贊達拉鍊金術 - 標題",["ID"]=591,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=930,["Flags"]=0},
  [375]={["Name_lang"]="破碎群島鍊金術 - 標題",["HordeName_lang"]="",["ID"]=593,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=940,["Flags"]=0},
  [376]={["Name_lang"]="德拉諾鍊金術 - 標題",["HordeName_lang"]="",["ID"]=594,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=950,["Flags"]=0},
  [377]={["Name_lang"]="潘達利亞鍊金術 - 標題",["HordeName_lang"]="",["ID"]=595,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=960,["Flags"]=0},
  [379]={["Name_lang"]="大災變鍊金術 - 標題",["HordeName_lang"]="",["ID"]=597,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=970,["Flags"]=0},
  [381]={["Name_lang"]="北裂境鍊金術 - 標題",["HordeName_lang"]="",["ID"]=599,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=980,["Flags"]=0},
  [383]={["Name_lang"]="外域鍊金術 - 標題",["HordeName_lang"]="",["ID"]=601,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=990,["Flags"]=0},
  [385]={["Name_lang"]="艾澤拉斯鍊金術 - 標題",["HordeName_lang"]="",["ID"]=603,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=999,["Flags"]=0},
  [428]={["Name_lang"]="庫爾提拉斯附魔 - 標題",["HordeName_lang"]="贊達拉附魔 - 標題",["ID"]=646,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=930,["Flags"]=0},
  [430]={["Name_lang"]="德拉諾附魔 - 標題",["HordeName_lang"]="",["ID"]=648,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=950,["Flags"]=0},
  [431]={["Name_lang"]="軍團附魔 - 標題",["HordeName_lang"]="",["ID"]=649,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=940,["Flags"]=0},
  [437]={["Name_lang"]="潘達利亞附魔 - 標題",["HordeName_lang"]="",["ID"]=655,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=960,["Flags"]=0},
  [442]={["Name_lang"]="大災變附魔 - 標題",["HordeName_lang"]="",["ID"]=660,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=970,["Flags"]=0},
  [444]={["Name_lang"]="北裂境附魔 - 標題",["HordeName_lang"]="",["ID"]=662,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=980,["Flags"]=0},
  [446]={["Name_lang"]="外域附魔 - 標題",["HordeName_lang"]="",["ID"]=664,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=990,["Flags"]=0},
  [448]={["Name_lang"]="艾澤拉斯附魔 - 標題",["HordeName_lang"]="",["ID"]=666,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=999,["Flags"]=0},
  [490]={["Name_lang"]="庫爾提拉斯工程學 - 標題",["HordeName_lang"]="贊達拉工程學 - 標題",["ID"]=708,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=930,["Flags"]=0},
  [492]={["Name_lang"]="軍團工程學 - 標題",["HordeName_lang"]="",["ID"]=710,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=940,["Flags"]=0},
  [493]={["Name_lang"]="德拉諾工程學 - 標題",["HordeName_lang"]="",["ID"]=711,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=950,["Flags"]=0},
  [494]={["Name_lang"]="潘達利亞工程學 - 標題",["HordeName_lang"]="",["ID"]=712,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=960,["Flags"]=0},
  [496]={["Name_lang"]="大災變工程學 - 標題",["HordeName_lang"]="",["ID"]=714,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=970,["Flags"]=0},
  [498]={["Name_lang"]="北裂境工程學 - 標題",["HordeName_lang"]="",["ID"]=716,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=980,["Flags"]=0},
  [500]={["Name_lang"]="外域工程學 - 標題",["HordeName_lang"]="",["ID"]=718,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=990,["Flags"]=0},
  [502]={["Name_lang"]="艾澤拉斯工程學 - 標題",["HordeName_lang"]="",["ID"]=720,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=999,["Flags"]=0},
  [540]={["Name_lang"]="庫爾提拉斯銘文學 - 標題",["HordeName_lang"]="贊達拉銘文學 - 標題",["ID"]=758,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=930,["Flags"]=0},
  [542]={["Name_lang"]="軍團銘文學 - 標題",["HordeName_lang"]="",["ID"]=760,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=940,["Flags"]=0},
  [543]={["Name_lang"]="德拉諾銘文學 - 標題",["HordeName_lang"]="",["ID"]=761,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=950,["Flags"]=0},
  [544]={["Name_lang"]="潘達利亞銘文學 - 標題",["HordeName_lang"]="",["ID"]=762,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=960,["Flags"]=0},
  [546]={["Name_lang"]="大災變銘文學 - 標題",["HordeName_lang"]="",["ID"]=764,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=970,["Flags"]=0},
  [548]={["Name_lang"]="北裂境銘文學 - 標題",["HordeName_lang"]="",["ID"]=766,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=980,["Flags"]=0},
  [550]={["Name_lang"]="外域銘文學 - 標題",["HordeName_lang"]="",["ID"]=768,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=990,["Flags"]=0},
  [552]={["Name_lang"]="艾澤拉斯銘文學 - 標題",["HordeName_lang"]="",["ID"]=770,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=999,["Flags"]=0},
  [586]={["Name_lang"]="庫爾提拉斯設計圖 - 標題",["HordeName_lang"]="贊達拉設計圖 - 標題",["ID"]=804,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=930,["Flags"]=0},
  [588]={["Name_lang"]="軍團設計圖 - 標題",["HordeName_lang"]="",["ID"]=806,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=940,["Flags"]=0},
  [589]={["Name_lang"]="德拉諾設計圖 - 標題",["HordeName_lang"]="",["ID"]=807,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=950,["Flags"]=0},
  [590]={["Name_lang"]="潘達利亞設計圖 - 標題",["HordeName_lang"]="",["ID"]=808,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=960,["Flags"]=0},
  [592]={["Name_lang"]="大災變設計圖 - 標題",["HordeName_lang"]="",["ID"]=810,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=970,["Flags"]=0},
  [594]={["Name_lang"]="北裂境設計圖 - 標題",["HordeName_lang"]="",["ID"]=812,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=980,["Flags"]=0},
  [596]={["Name_lang"]="外域設計圖 - 標題",["HordeName_lang"]="",["ID"]=814,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=990,["Flags"]=0},
  [598]={["Name_lang"]="艾澤拉斯設計圖 - 標題",["HordeName_lang"]="",["ID"]=816,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=999,["Flags"]=0},
  [652]={["Name_lang"]="庫爾提拉斯圖樣 - 標題",["HordeName_lang"]="贊達拉圖樣 - 標題",["ID"]=870,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=930,["Flags"]=0},
  [654]={["Name_lang"]="軍團圖樣 - 標題",["HordeName_lang"]="",["ID"]=872,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=940,["Flags"]=0},
  [655]={["Name_lang"]="德拉諾圖樣 - 標題",["HordeName_lang"]="",["ID"]=873,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=950,["Flags"]=0},
  [656]={["Name_lang"]="艾澤拉斯圖樣 - 標題",["HordeName_lang"]="",["ID"]=874,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=999,["Flags"]=0},
  [657]={["Name_lang"]="潘達利亞圖樣 - 標題",["HordeName_lang"]="",["ID"]=875,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=960,["Flags"]=0},
  [659]={["Name_lang"]="大災變圖樣 - 標題",["HordeName_lang"]="",["ID"]=877,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=970,["Flags"]=0},
  [661]={["Name_lang"]="北裂境圖樣 - 標題",["HordeName_lang"]="",["ID"]=879,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=980,["Flags"]=0},
  [663]={["Name_lang"]="外域圖樣 - 標題",["HordeName_lang"]="",["ID"]=881,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=990,["Flags"]=0},
  [723]={["Name_lang"]="庫爾提拉斯圖樣 - 標題",["HordeName_lang"]="贊達拉圖樣 - 標題",["ID"]=941,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=930,["Flags"]=0},
  [729]={["Name_lang"]="軍團圖樣 - 標題",["HordeName_lang"]="",["ID"]=947,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=940,["Flags"]=0},
  [730]={["Name_lang"]="德拉諾圖樣 - 標題",["HordeName_lang"]="",["ID"]=948,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=950,["Flags"]=0},
  [731]={["Name_lang"]="潘達利亞圖樣 - 標題",["HordeName_lang"]="",["ID"]=949,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=960,["Flags"]=0},
  [733]={["Name_lang"]="大災變圖樣 - 標題",["HordeName_lang"]="",["ID"]=951,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=970,["Flags"]=0},
  [735]={["Name_lang"]="北裂境圖樣 - 標題",["HordeName_lang"]="",["ID"]=953,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=980,["Flags"]=0},
  [737]={["Name_lang"]="外域圖樣 - 標題",["HordeName_lang"]="",["ID"]=955,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=990,["Flags"]=0},
  [739]={["Name_lang"]="艾澤拉斯圖樣 - 標題",["HordeName_lang"]="",["ID"]=957,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=999,["Flags"]=0},
  [795]={["Name_lang"]="德拉諾食物 - 標題",["HordeName_lang"]="",["ID"]=1013,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=950,["Flags"]=0},
  [796]={["Name_lang"]="破碎群島食物 - 標題",["HordeName_lang"]="",["ID"]=1014,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=940,["Flags"]=0},
  [797]={["Name_lang"]="熊貓人菜餚 - 標題",["HordeName_lang"]="",["ID"]=1015,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=960,["Flags"]=0},
  [798]={["Name_lang"]="舊世界食譜 - 標題",["HordeName_lang"]="",["ID"]=1016,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=999,["Flags"]=0},
  [799]={["Name_lang"]="外域風味菜餚 - 標題",["HordeName_lang"]="",["ID"]=1017,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=990,["Flags"]=0},
  [800]={["Name_lang"]="寒冷北方的食譜 - 標題",["HordeName_lang"]="",["ID"]=1018,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=980,["Flags"]=0},
  [801]={["Name_lang"]="大災變食譜 - 標題",["HordeName_lang"]="",["ID"]=1019,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=970,["Flags"]=0},
  [810]={["Name_lang"]="庫爾提拉斯草藥學 - 標題",["HordeName_lang"]="贊達拉草藥學 - 標題",["ID"]=1028,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=930,["Flags"]=0},
  [813]={["Name_lang"]="軍團草藥學 - 標題",["HordeName_lang"]="",["ID"]=1031,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=940,["Flags"]=0},
  [815]={["Name_lang"]="德拉諾草藥學 - 標題",["HordeName_lang"]="",["ID"]=1033,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=950,["Flags"]=0},
  [817]={["Name_lang"]="潘達利亞草藥學 - 標題",["HordeName_lang"]="",["ID"]=1035,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=960,["Flags"]=0},
  [819]={["Name_lang"]="大災變草藥學 - 標題",["HordeName_lang"]="",["ID"]=1037,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=970,["Flags"]=0},
  [821]={["Name_lang"]="北裂境草藥學 - 標題",["HordeName_lang"]="",["ID"]=1039,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=980,["Flags"]=0},
  [823]={["Name_lang"]="外域草藥學 - 標題",["HordeName_lang"]="",["ID"]=1041,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=990,["Flags"]=0},
  [825]={["Name_lang"]="艾澤拉斯草藥學 - 標題",["HordeName_lang"]="",["ID"]=1043,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=999,["Flags"]=0},
  [827]={["Name_lang"]="庫爾提拉斯剝皮 - 標題",["HordeName_lang"]="贊達拉剝皮 - 標題",["ID"]=1045,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=930,["Flags"]=0},
  [829]={["Name_lang"]="軍團剝皮 - 標題",["HordeName_lang"]="",["ID"]=1047,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=940,["Flags"]=0},
  [830]={["Name_lang"]="德拉諾剝皮 - 標題",["HordeName_lang"]="",["ID"]=1049,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=950,["Flags"]=0},
  [832]={["Name_lang"]="潘達利亞剝皮 - 標題",["HordeName_lang"]="",["ID"]=1051,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=960,["Flags"]=0},
  [834]={["Name_lang"]="大災變剝皮 - 標題",["HordeName_lang"]="",["ID"]=1053,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=970,["Flags"]=0},
  [836]={["Name_lang"]="北裂境剝皮 - 標題",["HordeName_lang"]="",["ID"]=1055,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=980,["Flags"]=0},
  [838]={["Name_lang"]="外域剝皮 - 標題",["HordeName_lang"]="",["ID"]=1057,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=990,["Flags"]=0},
  [840]={["Name_lang"]="艾澤拉斯剝皮 - 標題",["HordeName_lang"]="",["ID"]=1059,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=999,["Flags"]=0},
  [844]={["Name_lang"]="庫爾提拉斯採礦 - 標題",["HordeName_lang"]="贊達拉採礦 - 標題",["ID"]=1064,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=930,["Flags"]=0},
  [846]={["Name_lang"]="軍團採礦 - 標題",["HordeName_lang"]="",["ID"]=1066,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=940,["Flags"]=0},
  [847]={["Name_lang"]="德拉諾採礦 - 標題",["HordeName_lang"]="",["ID"]=1067,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=950,["Flags"]=0},
  [849]={["Name_lang"]="潘達利亞採礦 - 標題",["HordeName_lang"]="",["ID"]=1069,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=960,["Flags"]=0},
  [851]={["Name_lang"]="大災變採礦 - 標題",["HordeName_lang"]="",["ID"]=1071,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=970,["Flags"]=0},
  [853]={["Name_lang"]="北裂境採礦 - 標題",["HordeName_lang"]="",["ID"]=1073,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=980,["Flags"]=0},
  [855]={["Name_lang"]="外域採礦 - 標題",["HordeName_lang"]="",["ID"]=1075,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=990,["Flags"]=0},
  [857]={["Name_lang"]="艾澤拉斯採礦 - 標題",["HordeName_lang"]="",["ID"]=1077,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=999,["Flags"]=0},
  [877]={["Name_lang"]="艾澤拉斯釣魚 - 標題",["HordeName_lang"]="",["ID"]=1099,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=1000,["Flags"]=0},
  [879]={["Name_lang"]="外域釣魚 - 標題",["HordeName_lang"]="",["ID"]=1101,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=990,["Flags"]=0},
  [881]={["Name_lang"]="北裂境釣魚 - 標題",["HordeName_lang"]="",["ID"]=1103,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=980,["Flags"]=0},
  [883]={["Name_lang"]="大災變釣魚 - 標題",["HordeName_lang"]="",["ID"]=1105,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=970,["Flags"]=0},
  [885]={["Name_lang"]="潘達利亞釣魚 - 標題",["HordeName_lang"]="",["ID"]=1107,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=960,["Flags"]=0},
  [887]={["Name_lang"]="德拉諾釣魚 - 標題",["HordeName_lang"]="",["ID"]=1109,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=950,["Flags"]=0},
  [889]={["Name_lang"]="軍團釣魚 - 標題",["HordeName_lang"]="",["ID"]=1111,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=940,["Flags"]=0},
  [891]={["Name_lang"]="庫爾提拉斯釣魚 - 標題",["HordeName_lang"]="贊達拉釣魚 - 標題",["ID"]=1113,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=930,["Flags"]=0},
  [895]={["Name_lang"]="庫爾提拉斯烹飪 - 標題",["HordeName_lang"]="贊達拉烹飪 - 標題",["ID"]=1117,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=930,["Flags"]=0},
  [929]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=1250,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=0,["Flags"]=0},
  [932]={["Name_lang"]="訓練",["HordeName_lang"]="",["ID"]=1255,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=0,["Flags"]=0},
  [934]={["Name_lang"]="廢料場工程",["HordeName_lang"]="",["ID"]=1257,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2720,["OrderIndex"]=0,["Flags"]=0},
  [954]={["Name_lang"]="Shadowlands Alchemy - Header",["HordeName_lang"]="",["ID"]=1293,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=171,["OrderIndex"]=940,["Flags"]=0},
  [971]={["Name_lang"]="Shadowlands Blacksmithing - Header",["HordeName_lang"]="",["ID"]=1310,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=164,["OrderIndex"]=920,["Flags"]=0},
  [980]={["Name_lang"]="Shadowlands Mining - Header",["HordeName_lang"]="",["ID"]=1319,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=186,["OrderIndex"]=920,["Flags"]=0},
  [983]={["Name_lang"]="Shadowlands Cuisine - Header",["HordeName_lang"]="",["ID"]=1322,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=185,["OrderIndex"]=920,["Flags"]=0},
  [989]={["Name_lang"]="Shadowlands Skinning - Header",["HordeName_lang"]="",["ID"]=1330,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=393,["OrderIndex"]=920,["Flags"]=0},
  [992]={["Name_lang"]="Shadowlands Leatherworking - Header",["HordeName_lang"]="",["ID"]=1333,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=165,["OrderIndex"]=920,["Flags"]=0},
  [1007]={["Name_lang"]="Shadowlands Enchanting - Header",["HordeName_lang"]="",["ID"]=1363,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=333,["OrderIndex"]=920,["Flags"]=0},
  [1020]={["Name_lang"]="Shadowlands Engineering - Header",["HordeName_lang"]="",["ID"]=1380,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=202,["OrderIndex"]=920,["Flags"]=0},
  [1030]={["Name_lang"]="Shadowlands Fishing - Header",["HordeName_lang"]="",["ID"]=1390,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=356,["OrderIndex"]=920,["Flags"]=0},
  [1034]={["Name_lang"]="Shadowlands Tailoring - Header",["HordeName_lang"]="",["ID"]=1394,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=197,["OrderIndex"]=0,["Flags"]=0},
  [1044]={["Name_lang"]="Shadowlands Inscription - Header",["HordeName_lang"]="",["ID"]=1405,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=773,["OrderIndex"]=920,["Flags"]=0},
  [1055]={["Name_lang"]="Shadowlands Designs - Header",["HordeName_lang"]="",["ID"]=1417,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=755,["OrderIndex"]=920,["Flags"]=0},
  [1065]={["Name_lang"]="Shadowlands Herbalism - Header",["HordeName_lang"]="",["ID"]=1442,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=182,["OrderIndex"]=920,["Flags"]=0},
  [1067]={["Name_lang"]="靈魂暗語",["HordeName_lang"]="",["ID"]=1444,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2777,["OrderIndex"]=0,["Flags"]=0},
  [1080]={["Name_lang"]="憎惡縫合術",["HordeName_lang"]="",["ID"]=1478,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2787,["OrderIndex"]=0,["Flags"]=0},
  [1085]={["Name_lang"]="晉升工藝",["HordeName_lang"]="",["ID"]=1485,["ParentTradeSkillCategoryID"]=0,["SkillLineID"]=2791,["OrderIndex"]=0,["Flags"]=0},
}